//! Support-ticket report builder.
//!
//! Collects everything a maintainer needs to understand a bug report — app
//! version, host summary, the plan, and (when one exists) a failed run's
//! timeline — into a markdown report, and turns it into a prefilled
//! `github.com/…/issues/new` URL the user can open with one click.
//!
//! Nothing sensitive leaves the machine unreviewed: run inputs and outputs
//! are reduced to type-and-size shapes, and all free text (errors, the plan
//! YAML) passes through [`scrub_text`], which masks credentials, emails, and
//! home directories. The full report is also written to a local file so the
//! user can read exactly what the issue will contain before submitting.

use std::sync::LazyLock;

use regex::Regex;

use crate::executor::Run;
use crate::plan::types::Plan;
use crate::storage::runs::{StepRun, StepRunStatus};

/// Where the prefilled ticket is opened.
pub const ISSUES_NEW_URL: &str = "https://github.com/inxm-ai/inxm-local/issues/new";

/// Keep the whole prefilled URL under GitHub's ~8 KiB request-line limit,
/// with headroom for the title and query keys.
const MAX_ENCODED_BODY: usize = 6000;

/// Longest scrubbed error excerpt included per step.
const MAX_ERROR_CHARS: usize = 500;

// ─── Report input ─────────────────────────────────────────────────────────────

/// Everything the report is built from. All fields are optional except the
/// host facts, so a ticket can be created even before any plan exists.
pub struct SupportInfo<'a> {
    pub app_version: &'a str,
    /// One-line host summary (OS, interpreters, runners).
    pub environment: &'a str,
    /// Compiler backend label, e.g. "claude (sonnet)" — never credentials.
    pub backend: Option<&'a str>,
    pub plan: Option<&'a Plan>,
    pub run: Option<&'a Run>,
}

// ─── Report ───────────────────────────────────────────────────────────────────

/// A short issue title: the failing step and plan name when known.
pub fn issue_title(info: &SupportInfo) -> String {
    let failed_step = info.run.and_then(|run| match &run.status {
        crate::executor::RunStatus::Failed { failed_step_id, .. } => Some(failed_step_id.clone()),
        _ => None,
    });
    match (info.plan, failed_step) {
        (Some(plan), Some(step)) => {
            format!(
                "[support] \u{201c}{}\u{201d} fails at step \u{201c}{step}\u{201d}",
                plan.name
            )
        }
        (Some(plan), None) => format!("[support] Problem with \u{201c}{}\u{201d}", plan.name),
        _ => "[support] Problem report".to_owned(),
    }
}

/// The full markdown report. Every free-text field is scrubbed; run values
/// are reduced to shapes.
pub fn build_report(info: &SupportInfo) -> String {
    let mut out = String::new();

    out.push_str("## Support report\n\n");
    out.push_str(&format!(
        "| | |\n|---|---|\n| inxm-local | v{} |\n| Host | {} |\n| Compiler backend | {} |\n\n",
        info.app_version,
        scrub_text(info.environment),
        info.backend
            .map(scrub_text)
            .unwrap_or_else(|| "not configured".to_owned()),
    ));

    if let Some(plan) = info.plan {
        push_plan_section(&mut out, plan);
    }
    if let Some(run) = info.run {
        push_run_section(&mut out, run);
    }

    out.push_str(
        "---\n_Generated by inxm-local's support-ticket collector. Inputs, outputs, and \
         free text were anonymized (values reduced to type/size shapes; credentials, \
         emails, and home directories masked). Please review before submitting._\n",
    );
    out
}

fn push_plan_section(out: &mut String, plan: &Plan) {
    out.push_str(&format!(
        "## Plan \u{201c}{}\u{201d}\n\n- id: `{}` (v{})\n",
        plan.name, plan.metadata.id, plan.metadata.version
    ));
    if let Some(compiled_by) = &plan.metadata.compiled_by {
        out.push_str(&format!("- compiled by: {}\n", scrub_text(compiled_by)));
    }
    if let Some(intent) = &plan.metadata.intent {
        out.push_str(&format!("- intent: {}\n", scrub_text(intent)));
    }
    out.push_str("\n| step | type | depends on |\n|---|---|---|\n");
    for step in &plan.steps {
        out.push_str(&format!(
            "| `{}` | {} | {} |\n",
            step.id,
            step.step_type(),
            match step.depends_on.is_empty() {
                true => "—".to_owned(),
                false => format!("`{}`", step.depends_on.join("`, `")),
            }
        ));
    }
    out.push('\n');

    // The full definition is what makes compiler bugs reproducible; scrubbed
    // so literals like tokens or home paths inside step configs are masked.
    match serde_yaml::to_string(plan) {
        Ok(yaml) => out.push_str(&format!(
            "<details><summary>Full plan definition (scrubbed)</summary>\n\n```yaml\n{}```\n\n</details>\n\n",
            scrub_text(&yaml)
        )),
        Err(error) => out.push_str(&format!("_(plan could not be serialized: {error})_\n\n")),
    }
}

fn push_run_section(out: &mut String, run: &Run) {
    out.push_str(&format!(
        "## Run `{}`\n\n- status: {}\n- started: {}\n",
        run.id, run.status, run.started_at,
    ));
    if let Some(finished) = run.finished_at {
        out.push_str(&format!("- finished: {finished}\n"));
    }
    if !run.inputs.is_empty() {
        out.push_str(&format!(
            "- invocation inputs (anonymized): `{}`\n",
            serde_json::Value::Object(
                run.inputs
                    .iter()
                    .map(|(k, v)| (k.clone(), redact_json(v)))
                    .collect()
            )
        ));
    }

    out.push_str(
        "\n| step | status | attempt | duration | outputs (shape) |\n|---|---|---|---|---|\n",
    );
    for step_run in run.step_runs.values() {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} |\n",
            step_run.step_id,
            step_run.status,
            step_run.attempt,
            step_run
                .duration_ms
                .map(|ms| format!("{ms} ms"))
                .unwrap_or_else(|| "—".to_owned()),
            outputs_shape(step_run),
        ));
    }
    out.push('\n');

    for step_run in run.step_runs.values() {
        let Some(error) = &step_run.error else {
            continue;
        };
        out.push_str(&format!(
            "**Error in `{}`:**\n\n```\n{}\n```\n\n",
            step_run.step_id,
            truncate(&scrub_text(error), MAX_ERROR_CHARS),
        ));
    }
}

/// A compact type/size description of a step's outputs — never the values.
fn outputs_shape(step_run: &StepRun) -> String {
    if step_run.status != StepRunStatus::Succeeded && step_run.outputs.is_empty() {
        return "—".to_owned();
    }
    match step_run.outputs.is_empty() {
        true => "(none)".to_owned(),
        false => step_run
            .outputs
            .iter()
            .map(|(name, value)| format!("{name}: {}", shape_of(value)))
            .collect::<Vec<_>>()
            .join(", "),
    }
}

// ─── Anonymization ────────────────────────────────────────────────────────────

/// Replace every value with its type-and-size shape, preserving structure.
pub fn redact_json(value: &serde_json::Value) -> serde_json::Value {
    use serde_json::Value;
    match value {
        Value::Null => Value::Null,
        Value::Bool(b) => Value::Bool(*b),
        Value::Number(_) => Value::String("[number]".to_owned()),
        Value::String(s) => Value::String(format!("[string, {} chars]", s.chars().count())),
        Value::Array(items) => Value::Array(items.iter().map(redact_json).collect()),
        Value::Object(map) => Value::Object(
            map.iter()
                .map(|(k, v)| (k.clone(), redact_json(v)))
                .collect(),
        ),
    }
}

fn shape_of(value: &serde_json::Value) -> String {
    use serde_json::Value;
    match value {
        Value::Null => "null".to_owned(),
        Value::Bool(_) => "bool".to_owned(),
        Value::Number(_) => "number".to_owned(),
        Value::String(s) => format!("string ({} chars)", s.chars().count()),
        Value::Array(items) => format!("array ({} items)", items.len()),
        Value::Object(map) => format!("object ({} keys)", map.len()),
    }
}

static SECRET_ASSIGNMENT: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r#"(?i)\b(authorization|api[_-]?key|apikey|access[_-]?token|token|secret|password|passwd)("?\s*[:=]\s*"?)([^\s"',;&]+)"#,
    )
    .expect("static regex compiles")
});

static BEARER: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r#"(?i)\b(bearer)\s+[^\s"',;&]+"#).expect("static regex compiles"));

static KNOWN_KEY_SHAPES: LazyLock<Regex> = LazyLock::new(|| {
    // Anthropic/OpenAI-style keys, GitHub tokens, JWTs, AWS access key ids.
    Regex::new(
        r"\bsk-[A-Za-z0-9_-]{10,}|\bgh[pousr]_[A-Za-z0-9]{20,}|\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{5,}\.[A-Za-z0-9_-]{5,}|\bAKIA[0-9A-Z]{16}\b",
    )
    .expect("static regex compiles")
});

static EMAIL: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}").expect("static regex compiles")
});

static HOME_DIR: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r#"(?i)(/home/|/Users/|C:\\Users\\)[^/\\\s"']+"#).expect("static regex compiles")
});

/// Mask credentials, emails, and home directories in free text. Applied to
/// every user- or run-originated string that ends up in the report.
pub fn scrub_text(text: &str) -> String {
    let scrubbed = BEARER.replace_all(text, "$1 [REDACTED]");
    let scrubbed = SECRET_ASSIGNMENT.replace_all(&scrubbed, "$1$2[REDACTED]");
    let scrubbed = KNOWN_KEY_SHAPES.replace_all(&scrubbed, "[REDACTED]");
    let scrubbed = EMAIL.replace_all(&scrubbed, "[email]");
    HOME_DIR.replace_all(&scrubbed, "$1[user]").into_owned()
}

fn truncate(text: &str, max_chars: usize) -> String {
    match text.char_indices().nth(max_chars) {
        Some((idx, _)) => format!("{}…", &text[..idx]),
        None => text.to_owned(),
    }
}

// ─── GitHub issue URL ─────────────────────────────────────────────────────────

/// A `…/issues/new` URL with title and body prefilled. The body is truncated
/// (with a pointer to the local report file) so the URL stays within
/// GitHub's request-line limits.
pub fn issue_url(title: &str, body: &str, report_path: &str) -> String {
    let mut body = body.to_owned();
    if urlencode(&body).len() > MAX_ENCODED_BODY {
        let notice = format!(
            "\n\n---\n_Report truncated to fit the URL — the full report was saved to \
             `{}`; please attach it to this issue._\n",
            scrub_text(report_path)
        );
        let mut keep = body.chars().count();
        loop {
            keep = keep * 3 / 4;
            let truncated = format!("{}…{notice}", truncate_raw(&body, keep));
            if urlencode(&truncated).len() <= MAX_ENCODED_BODY || keep == 0 {
                body = truncated;
                break;
            }
        }
    }
    format!(
        "{ISSUES_NEW_URL}?title={}&body={}",
        urlencode(title),
        urlencode(&body)
    )
}

fn truncate_raw(text: &str, max_chars: usize) -> &str {
    match text.char_indices().nth(max_chars) {
        Some((idx, _)) => &text[..idx],
        None => text,
    }
}

/// Percent-encode for a query-string value (RFC 3986 unreserved set).
fn urlencode(text: &str) -> String {
    let mut out = String::with_capacity(text.len() * 3);
    for byte in text.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(byte as char)
            }
            _ => out.push_str(&format!("%{byte:02X}")),
        }
    }
    out
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::executor::RunStatus;
    use crate::storage::runs::StepRun;

    fn failed_run() -> Run {
        let mut run = Run::new("plan-1", 3);
        run.status = RunStatus::Failed {
            failed_step_id: "fetch".to_owned(),
            message: "HTTP 503".to_owned(),
        };
        run.inputs
            .insert("city".to_owned(), serde_json::json!("Munich"));
        run.inputs.insert("limit".to_owned(), serde_json::json!(5));
        let mut step = StepRun::new("fetch");
        step.status = StepRunStatus::Failed;
        step.attempt = 3;
        step.error = Some(
            "HTTP 503 from https://api.example.com?key=sk-abc1234567890xyz for bob@example.com"
                .to_owned(),
        );
        run.step_runs.insert("fetch".to_owned(), step);
        let mut ok = StepRun::new("echo");
        ok.status = StepRunStatus::Succeeded;
        ok.outputs
            .insert("stdout".to_owned(), serde_json::json!("secret city name"));
        run.step_runs.insert("echo".to_owned(), ok);
        run
    }

    #[test]
    fn scrub_masks_credentials_emails_and_home_dirs() {
        let scrubbed = scrub_text(
            "token=abc123 Authorization: Bearer xyz.secret /home/alice/data \
             C:\\Users\\Bob\\file mail bob@example.com key sk-proj1234567890abc",
        );
        assert!(!scrubbed.contains("abc123"), "{scrubbed}");
        assert!(!scrubbed.contains("xyz.secret"), "{scrubbed}");
        assert!(!scrubbed.contains("alice"), "{scrubbed}");
        assert!(!scrubbed.contains("Bob"), "{scrubbed}");
        assert!(!scrubbed.contains("bob@example.com"), "{scrubbed}");
        assert!(!scrubbed.contains("sk-proj"), "{scrubbed}");
        assert!(scrubbed.contains("/home/[user]"), "{scrubbed}");
        assert!(scrubbed.contains("[email]"), "{scrubbed}");
    }

    #[test]
    fn redact_json_keeps_structure_but_not_values() {
        let redacted = redact_json(&serde_json::json!({
            "city": "Munich", "limit": 5, "fresh": true,
            "nested": {"key": "value"}, "list": ["a", 1]
        }));
        assert_eq!(redacted["city"], "[string, 6 chars]");
        assert_eq!(redacted["limit"], "[number]");
        assert_eq!(redacted["fresh"], true);
        assert_eq!(redacted["nested"]["key"], "[string, 5 chars]");
        assert_eq!(redacted["list"][0], "[string, 1 chars]");
        assert_eq!(redacted["list"][1], "[number]");
    }

    #[test]
    fn report_contains_run_timeline_but_no_raw_values() {
        let run = failed_run();
        let info = SupportInfo {
            app_version: "0.1.0",
            environment: "linux (x86_64)",
            backend: Some("claude"),
            plan: None,
            run: Some(&run),
        };
        let report = build_report(&info);
        assert!(report.contains("v0.1.0"));
        assert!(report.contains("| `fetch` | failed | 3 |"), "{report}");
        assert!(report.contains("HTTP 503"), "{report}");
        // The input value and the successful step's output never appear.
        assert!(!report.contains("Munich"), "{report}");
        assert!(!report.contains("secret city name"), "{report}");
        // Credentials/emails inside the error are masked.
        assert!(!report.contains("sk-abc"), "{report}");
        assert!(!report.contains("bob@example.com"), "{report}");
    }

    #[test]
    fn issue_url_is_prefilled_and_bounded() {
        let url = issue_url("[support] test", "short body", "/tmp/report.md");
        assert!(url.starts_with(ISSUES_NEW_URL));
        assert!(url.contains("title=%5Bsupport%5D%20test"));
        assert!(url.contains("body=short%20body"));

        let long = "x".repeat(50_000);
        let url = issue_url("t", &long, "/home/alice/report.md");
        assert!(url.len() < 8_000, "url length {}", url.len());
        assert!(
            urlencode("Report truncated")
                .split("%20")
                .all(|part| url.contains(part))
        );
        assert!(!url.contains("alice"), "report path must be scrubbed too");
    }

    #[test]
    fn titles_name_the_plan_and_failing_step() {
        let run = failed_run();
        let info = SupportInfo {
            app_version: "0.1.0",
            environment: "linux",
            backend: None,
            plan: None,
            run: Some(&run),
        };
        assert_eq!(issue_title(&info), "[support] Problem report");
    }
}
